### ISSUE TITLE
View Links

### ISSUE THREAD

**Issue by C4L86** [omahacodeschool/old_vinyl-archive#129]
- [ ] Sidebar Master
  - [x] link to area index
  - [x] link to area show
  - [x] link to genre index
  - [x] link to genre show
  - [x] link to decade index
  - [ ] link to decade show (doesn't exist yet)
  - [x] link to format index
  - [x] link to format show
- [x] Homepage (Album index)
  - [x] link to album show
  - [x] link to artist show
- [x] Album show
  - [x] link to artist show
  - [x] link to area show
  - [x] link to format show
  - [x] link to genre show
- [x] Artist index
  - [x] link to artist show
  - [x] link to album show
  - [x] turn album images into links
- [x] Artist show
  - [x] link to album show
  - [x] turn album images into links
- [x] Area index
  - [x] link to area show
  - [x] link to album show
  - [x] link to artist show
- [x] Area show
  - [x] link to album show
  - [x] link to artist show
- [x] Genre index 
  - [x] link to genre show
  - [x] link to album show
  - [x] link to artist show
- [x] Genre show
  - [x] link to album show
  - [x] link to artist show
- [x] Decade index
  - [ ] link to decade show
  - [x] link to album show
  - [x] link to artist show
- [ ] Decade show
  - [ ] link to album show
  - [ ] link to artist show
- [x] Format index
  - [x] link to format show
  - [x] link to album show
  - [x] link to artist show
- [x] Format show
  - [x] link to album show
  - [x] link to artist show
- [ ] Album addition page (user)
  - [ ] link to album show
  - [ ] link to artist show
- [ ] Review submissions (admin)

**Comment by jillianw** [comment]
Are we going to do the "require" thing and perhaps not actually need HN/VA links added to each page? I can't remember how it works...

**Comment by C4L86** [comment]
I imagine that there's a way to DRY up those links so we can leave those be for now. If anything we can just add them later
